### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/oXygen-MEI-addon#1]
Most people, myself included, have experience with oXygen but none with adding frameworks / add-ons. So, can you provide download and installation instructions for the add-on please, say as an addendum to README.md?

**Comment by rettinghaus** [comment]
see bwbohl/oXygen-MEI-addon/issues/4

**Comment by rettinghaus** [comment]
Which one is the main repo?

**Comment by bwbohl** [comment]
The main (and now only) repo is this here (https://github.com/music-encoding/oXygen-MEI-addon). Moreover 812f6b5ae03155ea95ebe5882726724747545bd1 introduced documentation in the [docs/](https://github.com/music-encoding/oXygen-MEI-addon/tree/develop/docs) directory, so far covering [installation](https://github.com/music-encoding/oXygen-MEI-addon/tree/develop/docs/installation.md) and [build instructions](https://github.com/music-encoding/oXygen-MEI-addon/tree/develop/docs/build-instructions.md)
