### ISSUE TITLE
Install instruction URL?

### ISSUE THREAD

**Issue by riannella** [music-encoding/oXygen-MEI-addon#16]
Hi, what is the URL for the install instructions:
`  Enter the following URL in the line labeled “Show add-ons from”:`

**Comment by bwbohl** [comment]
Sorry for not having seen this until now… currently there is no publicly available add-on site serving this add-on. But you can choose a local file.
Although the release is quite old you might want to try the 0.1.0-alpha release assets.

1. Go to https://github.com/music-encoding/oXygen-MEI-addon/releases
2. expand the view of the Assets
3. Download oXygen-MEI-addon_v0.1.0-alpha.zip and oXygen-MEI-addon.xml and put them in a folder next to each other
4. form oxygen select the  oXygen-MEI-addon.xml as URL, and there you go

**Comment by riannella** [comment]
thanks
